FROM java:8

ENV LANG C.UTF-8
ENV LANGUAGE C
ENV LC_ALL C.UTF-8

RUN mkdir /spigot
RUN mkdir -p /var/lib/spigot
WORKDIR /spigot
RUN wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
RUN java -jar BuildTools.jar

VOLUME /var/lib/spigot
EXPOSE 25565

ADD ./start_docker.sh /
ENTRYPOINT bash /start_docker.sh
