#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto '
alias grep='grep --color=auto '

if [[ ${TERM} == "linux" ]]; then
	LANG='en_US.UTF-8'
fi
alias ll="ls -l"
alias la="ls -a"
