autoload -U compinit promptinit colors
compinit
promptinit
colors

# This will set the default prompt to the walters theme
# prompt suse

bindkey "\e[1~" beginning-of-line # Home
bindkey "\e[4~" end-of-line # End
bindkey "\e[5~" beginning-of-history # PageUp
bindkey "\e[6~" end-of-history # PageDown
bindkey "\e[2~" quoted-insert # Ins
bindkey "\e[3~" delete-char # Del
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey "\e[Z" reverse-menu-complete # Shift+Tab
# for rxvt
bindkey "\e[7~" beginning-of-line # Home
bindkey "\e[8~" end-of-line # End
# for non RH/Debian xterm, can't hurt for RH/Debian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
# for freebsd console
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

export EDITOR="vim"
if [[ ${TERM} == "linux" ]]; then
	export LANG='en_US.UTF-8'
fi
alias ls='ls --color=auto '
alias ll='ls -l '
alias lx='ls -l -a '
alias grep='grep --color=auto '

source /home/niko/.zsh/git-prompt/zshrc.sh

PROMPT='%{$terminfo[bold]$fg[green]%}%n%{$reset_color%}%{$terminfo[bold]$fg[green]%}@%m %{$fg[yellow]%}%1~ %{$reset_color%}$(git_super_status)%{$terminfo[bold]$fg[blue]%}>%{$reset_color%} '

